### ISSUE TITLE
Pure Nim/no regex Markdown

### ISSUE THREAD

**Issue by metagn** [nim-lang/needed-libraries#113]
All Nim libraries I could find for Markdown depend on C. https://github.com/soasme/nim-markdown, https://github.com/ruivieira/nim-slimdown (this one is limited) both use regex, which depends on PCRE, and quite frankly I don't like regex being used for parsing in real applications. nim-markdown also uses inheritance over case objects for tokens

[HastyScribe](https://github.com/h3rald/hastyscribe) seems to wrap [Discount](https://github.com/Orc/discount), a C implementation. The [wrapper](https://github.com/h3rald/hastyscribe/blob/master/src/hastyscribepkg/markdown.nim) should be its own package though, instead it's just a module in this package.

If anyone knows of an existing pure Markdown parser that I didn't mention, please inform

Edit: Forgot to mention there is a [hoedown](https://github.com/hoedown/hoedown) wrapper at https://github.com/Varriount/midnight_dynamite

**Comment by Araq** [comment]
Nim's RST parser supports markdown too and doesn't use C libraries nor regular expressions. Nim's forum uses it, it's well supported and was audited for security problems.

**Comment by metagn** [comment]
Does seem pretty useful, except the documented way of importing it (`packages/docutils/rst`) didn't work for me and I had to install it as a Nimble package, for which I had to remove the `name` attribute from its .nimble file. The documentation might take some time to digest. I'll try to use it for the time being and see if it works out

**Comment by metagn** [comment]
I wrote my own custom derivation of Markdown and the RST parser seems to work for most people's needs. Closing
