### ISSUE TITLE
JS regex wrapper

### ISSUE THREAD

**Issue by metagn** [nim-lang/needed-libraries#114]
There's regex libraries that wrap PCRE and ones written in pure Nim, yet none that uses pure JS regex syntax. This would be a start:

```nim
type RegExp {.importc: "RegExp".} = ref object

proc escapeSlashes(s: string): string =
  var escaped = false
  for ch in s:
    if escaped or ch == '/':
      result.add('\\')
      result.add(ch)
      escaped = false
    elif ch == '\\':
      escaped = true
    else:
      result.add(ch)

proc re(str: static[string]): RegExp =
  {.emit: [result, " = /", escapeSlashes(str), "/;"].}

let regexp = re"aDa+dd"
```

Of course you could also wrap `new RegExp` but MDN says it's slower for constant patterns.

**Comment by Araq** [comment]
> MDN says it's slower for constant patterns.

I doubt it, modern JITs should be really good at it.

**Comment by metagn** [comment]
That's what I thought at first. [MDN link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Creating_a_regular_expression). There are also some benchmarks online if you search "regexp constructor vs literal", [this one](https://www.measurethat.net/Benchmarks/Show/5347/0/regexp-constructor-vs-literal-vs-premade-constructing-i) shows a 3x speedup on Chrome. Doesn't seem like it's going to be that much of a difference in realtime though if it's still millions of operations per second.

**Comment by ghost** [comment]
`jsre` is now in devel.
