### ISSUE TITLE
Simple gui, like tkinter or wxwidgets.

### ISSUE THREAD

**Issue by alehander42** [nim-lang/needed-libraries#18]
(From Nim community survey 2017)

**Comment by Skrylar** [comment]
https://github.com/Skrylar/nfltk (in testing)

**Comment by treeform** [comment]
Duplicate of https://github.com/nim-lang/needed-libraries/issues/67 ?

**Comment by treeform** [comment]
Duplicate: https://github.com/nim-lang/needed-libraries/issues/55

**Comment by alehander42** [comment]
Ok, =>  #67
