### ISSUE TITLE
Better redis client

### ISSUE THREAD

**Issue by alehander42** [nim-lang/needed-libraries#62]
(From Nim community survey 2017)

**Comment by euantorano** [comment]
I'm not sure that this counts as a wrapper as such.

There is already [the official redis client](https://github.com/nim-lang/redis) which I recently added async support to, and am open to further improving. If there are any firm ideas of what's wrong with the current library and how it could be improved, please open issues on that repository and I will see what I can do if I have time.

**Comment by alehander42** [comment]
Well that's all I have about redis from the survey so I don't know what was the motivation for it :D I'll close it for now, people can follow the link from this issue and reopen it if there is a need
