### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by alehander92** [nim-lang/needed-libraries#64]
(From Nim community survey 2017)

**Comment by alehander42** [comment]
Great, I've seen the first one but I wasn't sure how many people use it

**Comment by treeform** [comment]
The author appears to have abandoned us...

**Comment by metagn** [comment]
I'm currently maintaining https://github.com/niv/websocket.nim, is that enough for this to be closed?

**Comment by treeform** [comment]
I think we should close this. We have two libs that work with this now.
