### ISSUE TITLE
Fast low level socket library (epool, kqueue)

### ISSUE THREAD

**Issue by alehander92** [nim-lang/needed-libraries#68]
(From Nim community survey 2017)

**Comment by FedericoCeratto** [comment]
io_uring is becoming very relevant: https://lwn.net/Articles/810414/

**Comment by dom96** [comment]
IMO this is already available: selectors module in stdlib (and its deps).

**Comment by FedericoCeratto** [comment]
From selectors doc:

> Partially supported OS: Windows (only sockets and user events), Solaris (files, sockets, handles and user events). Android (files, sockets, handles and user events).
> TODO: /dev/poll, event ports and filesystem events.

Maybe the issue should not be closed without benchmarks and/or mentioning io_uring as well.
There are also people asking for libev/libevent integration.
