### ISSUE TITLE
Green threads.

### ISSUE THREAD

**Issue by treeform** [nim-lang/needed-libraries#72]
I don't think async/await is that great for programming. I love the idea of green threads similar to `Gevent` from `python`.

Has any one looked into http://libmill.org/ ?
Has any one looked into pth https://www.gnu.org/software/pth/ ?

Some other links:

* http://www.gevent.org/index.html
* https://c9x.me/articles/gthreads/intro.html

**Comment by dom96** [comment]
Sounds like a fun project :)

**Comment by mamcx** [comment]
Or better, go-style channels.

**Comment by Jeff-Ciesielski** [comment]
I've been playing a bit with the coro module at work trying to develop a more-or-less drop in replacement for spawn + channels with cooperative task switching.  It works in a general sense for concurrency without parallelism, but I've hit some snags on the networking side as the socket module doesn't cleanly expose non-blocking sockets.  

As we continue to roll out Nim in-house, if we end up switching away from threads to coroutines, I'll open-source our libraries and (if appropriate) upstream things into the stdlib.

**Comment by treeform** [comment]
coro https://github.com/clibs/coro looks pretty cool. I like its small size. 

There are two things I don't like about nim's async stuff is:

* You have to type a lot of these {.async.}/Future[] everywhere. If I have sync code and now I want to do some thing async, it appears to have to sprinkle {.async.}/Future[] and figure out data flow problems everywhere. 

* If you are using c libraries that can't know about {.async.}/Future[] everything just blocks. I don't know how to solve this though, gevent from python has same issues. Libuvs wraps bunch of c calls that are blocking in threads. Maybe there is a way to mark calls to C with "do it magically in another thread, async me the results when its done"

**Comment by treeform** [comment]
After using async/await for a year, I think its good enough. I don't need this any more.
